# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c3pm_ui.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(561, 603)
        MainWindow.setAnimated(True)
        MainWindow.setDocumentMode(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_version = QtWidgets.QLabel(self.centralwidget)
        self.label_version.setGeometry(QtCore.QRect(180, 60, 341, 20))
        font = QtGui.QFont()
        font.setPointSize(6)
        self.label_version.setFont(font)
        self.label_version.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_version.setObjectName("label_version")
        self.label_title = QtWidgets.QLabel(self.centralwidget)
        self.label_title.setGeometry(QtCore.QRect(0, 10, 571, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.label_title.setFont(font)
        self.label_title.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_title.setObjectName("label_title")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(30, 150, 501, 141))
        self.groupBox.setObjectName("groupBox")
        self.label_mainProject = QtWidgets.QLabel(self.groupBox)
        self.label_mainProject.setGeometry(QtCore.QRect(10, 30, 301, 16))
        self.label_mainProject.setObjectName("label_mainProject")
        self.label_mergeProject = QtWidgets.QLabel(self.groupBox)
        self.label_mergeProject.setGeometry(QtCore.QRect(10, 80, 301, 16))
        self.label_mergeProject.setObjectName("label_mergeProject")
        self.lineEdit_mainProject = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_mainProject.setGeometry(QtCore.QRect(10, 50, 391, 22))
        self.lineEdit_mainProject.setObjectName("lineEdit_mainProject")
        self.lineEdit_mergeProject = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit_mergeProject.setGeometry(QtCore.QRect(10, 100, 391, 22))
        self.lineEdit_mergeProject.setObjectName("lineEdit_mergeProject")
        self.button_searchMainProject = QtWidgets.QPushButton(self.groupBox)
        self.button_searchMainProject.setGeometry(QtCore.QRect(410, 50, 81, 21))
        self.button_searchMainProject.setObjectName("button_searchMainProject")
        self.button_searchMergeProject = QtWidgets.QPushButton(self.groupBox)
        self.button_searchMergeProject.setGeometry(QtCore.QRect(410, 100, 81, 21))
        self.button_searchMergeProject.setObjectName("button_searchMergeProject")
        self.button_mergeProjects = QtWidgets.QPushButton(self.centralwidget)
        self.button_mergeProjects.setGeometry(QtCore.QRect(80, 510, 401, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.button_mergeProjects.setFont(font)
        self.button_mergeProjects.setObjectName("button_mergeProjects")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setEnabled(True)
        self.groupBox_2.setGeometry(QtCore.QRect(30, 300, 501, 191))
        self.groupBox_2.setObjectName("groupBox_2")
        self.lineEdit_exportPath = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_exportPath.setGeometry(QtCore.QRect(10, 50, 391, 22))
        self.lineEdit_exportPath.setObjectName("lineEdit_exportPath")
        self.label_exportPath = QtWidgets.QLabel(self.groupBox_2)
        self.label_exportPath.setGeometry(QtCore.QRect(10, 30, 81, 16))
        self.label_exportPath.setObjectName("label_exportPath")
        self.label_exportedFileName = QtWidgets.QLabel(self.groupBox_2)
        self.label_exportedFileName.setGeometry(QtCore.QRect(10, 80, 141, 16))
        self.label_exportedFileName.setObjectName("label_exportedFileName")
        self.lineEdir_fileName = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdir_fileName.setGeometry(QtCore.QRect(10, 100, 481, 22))
        self.lineEdir_fileName.setObjectName("lineEdir_fileName")
        self.checkBox_overwriteFiles = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_overwriteFiles.setGeometry(QtCore.QRect(10, 150, 341, 20))
        self.checkBox_overwriteFiles.setObjectName("checkBox_overwriteFiles")
        self.checkBox_folderProject = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_folderProject.setGeometry(QtCore.QRect(10, 130, 281, 20))
        self.checkBox_folderProject.setChecked(False)
        self.checkBox_folderProject.setObjectName("checkBox_folderProject")
        self.button_searchExportPath = QtWidgets.QPushButton(self.groupBox_2)
        self.button_searchExportPath.setGeometry(QtCore.QRect(410, 50, 81, 21))
        self.button_searchExportPath.setObjectName("button_searchExportPath")
        self.label_explain = QtWidgets.QLabel(self.centralwidget)
        self.label_explain.setGeometry(QtCore.QRect(60, 90, 441, 51))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_explain.setFont(font)
        self.label_explain.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_explain.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.label_explain.setWordWrap(True)
        self.label_explain.setObjectName("label_explain")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 561, 26))
        self.menubar.setObjectName("menubar")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.menuAbout.addAction(self.actionAbout)
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "C3PM"))
        self.label_version.setText(_translate("MainWindow", "Version"))
        self.label_title.setText(_translate("MainWindow", "Construct 3 Project Merger"))
        self.groupBox.setTitle(_translate("MainWindow", "Merge projects"))
        self.label_mainProject.setText(_translate("MainWindow", "Main project"))
        self.label_mergeProject.setText(_translate("MainWindow", "Secondary project"))
        self.button_searchMainProject.setText(_translate("MainWindow", "Search"))
        self.button_searchMergeProject.setText(_translate("MainWindow", "Search"))
        self.button_mergeProjects.setText(_translate("MainWindow", "Merge projects"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Output options"))
        self.lineEdit_exportPath.setText(_translate("MainWindow", "export/"))
        self.label_exportPath.setText(_translate("MainWindow", "Export path"))
        self.label_exportedFileName.setText(_translate("MainWindow", "Exported file name"))
        self.lineEdir_fileName.setText(_translate("MainWindow", "project_name"))
        self.checkBox_overwriteFiles.setText(_translate("MainWindow", "Overwrite repeated files (not recommended)"))
        self.checkBox_folderProject.setText(_translate("MainWindow", "Export as project folder"))
        self.button_searchExportPath.setText(_translate("MainWindow", "Search"))
        self.label_explain.setText(_translate("MainWindow", "Merge two Construct 3 projects into one. The resulting project will have files from both projects but it will keep the project properties of the one selected as the Main project"))
        self.menuAbout.setTitle(_translate("MainWindow", "Help"))
        self.actionAbout.setText(_translate("MainWindow", "About"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
